name: Achievements

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate Achievements
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Trophy SVG
        run: |
          curl -o dist/achievements.svg "https://github-profile-trophy.vercel.app/?username=dhruvanbhalara&theme=nord&column=4&margin-w=15&margin-h=15&no-frame=true"
      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/achievements.svg
          git commit -m "chore: update achievements" || exit 0
          git push
