name: Achievements

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Generate Achievements
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Schweinepriester/github-profile-achievements@v1
        with:
          token: ${{ secrets.README_TOKEN }}
          user: dhruvanbhalara
          out_path: dist/achievements.svg
          style: flat
          limit: 8
      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/achievements.svg
          git commit -m "chore: update achievements" || exit 0
          git push
